/*
 * This source file was generated by the Gradle 'init' task
 */
package uppgift_2;

import uppgift_3.Main1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //Main1.main(args);
    }
}
