/*
 * This source file was generated by the Gradle 'init' task
 */
package uppgift_2;

import UWU2.CommandRunner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        CommandRunner.run(null, null);
    }
}
